version: "3"

services:
  server:
    build: ./server
    container_name: server
    ports:
      - 3001:3001
    volumes:
      - ./server:/usr/src/app/server
      - node_modules:/usr/src/app/server/node_modules
    networks:
      - app-network
    env_file:
      - ./server/.env
    command: /usr/src/app/server/node_modules/.bin/nodemon server.js

  client:
    build: ./client
    container_name: client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app/client
      - node_modules:/usr/src/app/client/node_modules
    links:
      - server
    networks:
      - app-network
    env_file:
      - ./client/.env
    command: npm start

  db:
    image: mongo:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

volumes:
  dbdata:
  node_modules:

networks:
  app-network:
    driver: bridge
